project_id = "lqfqxspaamzhtgxhvlib"

[functions.import-products]
verify_jwt = false

[functions.exact-auth]
verify_jwt = false

[functions.exact-auth-callback]
verify_jwt = false

[functions.exact-api]
verify_jwt = false

[functions.exact-webhook]
verify_jwt = false

[functions.exact-webhooks-manage]
verify_jwt = false

[functions.exact-sync-customers]
verify_jwt = false

[functions.exact-sync-invoices]
verify_jwt = false

[functions.tradeplace-config]
verify_jwt = false

[functions.tradeplace-availability]
verify_jwt = false

[functions.tradeplace-order]
verify_jwt = false

[functions.tradeplace-webhook]
verify_jwt = false