// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqfqxspaamzhtgxhvlib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZnF4c3BhYW16aHRneGh2bGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODgzOTIsImV4cCI6MjA4NTM2NDM5Mn0.GOrfHdV_Vahceqmmn8MajLLJbQan3TF6iQOHB-lGQeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});